[project]
name = "unfair-lectures"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipython>=9.1.0",
    "joblib>=1.4.2",
    "openai>=1.73.0",
    "pysubs2>=1.8.0",
    "tqdm-joblib>=0.0.4",
]
